name: Test

on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:

env:
  NCBI_API_KEY: ${{ secrets.NCBI_API_KEY }}
  NCBI_MAIL: ${{ secrets.NCBI_MAIL }}

jobs:
  test-backend:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        python-version: ["3.10", "3.11", "3.12"]
        os: [ubuntu-latest]
        #os: [ ubuntu-latest, windows-latest ]

    steps:
      - uses: actions/checkout@v4

      - name: Debug Secrets
        run: |
            if [ -z "$NCBI_API_KEY" ]; then echo "NCBI_API_KEY is NOT set"; else echo "NCBI_API_KEY is SET"; fi
            if [ -z "$NCBI_MAIL" ]; then echo "NCBI_MAIL is NOT set"; else echo "NCBI_MAIL is SET"; fi

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          
      #----------------------------------------------
      #          install & configure poetry
      #----------------------------------------------
      - name: Install Poetry
        uses: snok/install-poetry@v1

      #----------------------------------------------
      #    install your root project, if required
      #----------------------------------------------
      - name: Install library
        run: poetry install --no-interaction

      #----------------------------------------------
      #              run pytest
      #----------------------------------------------
      - name: Run tests
        run: poetry run pytest tests

